language: cpp

sudo: false

addons:
  apt:
    packages:
      - liblog4cpp5-dev

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install libconfig log4cpp; fi

install:
  - curl -L https://github.com/nukedzn/psocksxx/releases/download/v1.1.1/psocksxx-1.1.1.tar.gz | tar -zx -C /tmp
  - cd /tmp/psocksxx-* && ./configure --prefix=/tmp/root && make && make install
  - if [ $TRAVIS_OS_NAME == linux ]; then curl -L http://www.hyperrealm.com/packages/libconfig-1.4.10.tar.gz | tar -zx -C /tmp; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then cd /tmp/libconfig-* && ./configure --prefix=/tmp/root && make && make install; fi
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  - if [ $TRAVIS_OS_NAME == linux ]; then libtoolize; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then glibtoolize; fi
  - aclocal
  - autoheader
  - autoconf
  - automake --add-missing
  - export PKG_CONFIG_PATH=/tmp/root/lib/pkgconfig && ./configure

script:
  - make distcheck

os:
  - linux
  - osx

